config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :only=>[:index]
  resources :movies do
    resources :roles
  end
  resources :trailers
  resources :actors
  resources :ratings, :except=>[:show,:index]

  root 'movies#index'

end

app/models/actor.rb
# == Schema Information
#
# Table name: actors
#
#  id         :integer          not null, primary key
#  first      :string(255)
#  last       :string(255)
#  gender     :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Actor < ActiveRecord::Base
  
  validates :last, presence:true
  validates :gender, :inclusion=>{:in=>%w(M F)}
  
  #has_and_belongs_to_many :movies
  has_many  :roles, dependent: :destroy
  has_many  :movies, :through=>:roles
  
  has_many  :ratings, as: :rateable, dependent: :destroy
  
  scope :males, -> { where(gender:'M') }
  scope :females, -> { where(gender:'F') }
  
  def fullname
    self.first + " " + self.last
  end
  
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  
  # before_action :authenticate_user!, except:[:index,:show]
  
  load_and_authorize_resource

  def new
    @actor = Actor.new
  end
  
  def create
    @actor = Actor.new(actor_params)
    if @actor.save
      redirect_to @actor, notice: 'actor successfully created'
    else
      render :new
    end
  end
  
  def edit
    @actor = Actor.find(params[:id])
  end
  
  def update
    @actor = Actor.find(params[:id])
    if @actor.update_attributes(actor_params)
      redirect_to @actor, notice: 'actor successfully updated'
    else
      render :edit
    end
  end
  
  def index
    @actors = Actor.order(:last, :first)
  end
  
  def show
    @actor = Actor.find(params[:id])
  end
  
  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy
    redirect_to actors_path, notice: 'actor successfully destroyed'
  end
  
  private
  
  def actor_params
    params[:actor].permit(:first, :last, :gender, {:movie_ids=>[]})
  end
  
end

app/helpers/actors_helper.rb
module ActorsHelper
  
  def show_fullname(actor)
  	  link_to "#{actor.fullname}", actor_path(actor)
	end
  
end

app/views/actors/_actor.html.erb
<tr>
	<td><%= show_fullname(actor) %></td>
	<td><%= actor.gender %></td>
  <td>
  	<%= link_to 'edit', edit_actor_path(actor), class:'btn btn-xs btn-default' %>
  	<%= link_to 'delete', actor, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-xs btn-danger" %>
	</td>
</tr>

app/views/actors/_form.html.erb
<div class="row col-md-10 col-md-offset-1">
<h1><%= controller.action_name %> actor</h1>
<%= simple_form_for(@actor, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f| %>
	<%= f.error_notification %>
	<%= f.input :first, hint:'required' %>
	<%= f.input :last, hint:'required' %>
	<%= f.input :gender, collection:%w(M F) %>
	<div class="row">
		<%= f.association :movies, as: :check_boxes, label_method: :title %>
	</div>
	<div class="row text-center">
		<%= f.submit nil, class:'btn btn-primary' %>
		<%= link_to 'back', :back, class:'btn btn-default' %>
	</div>
<% end %>
</div>

app/views/actors/edit.html.erb
<%= render 'form' %>

app/views/actors/index.html.erb
<div class="row">
	
	<h1 class="text-center">all actors</h1>

	<table class="table table-striped">
	  <thead>
	    <tr>
	      <th>name</th>
				<th>gender</th>
				<th>actions</th>
	    </tr>
	  </thead>

	  <tbody>
	    <%= render @actors %>
	  </tbody>
	</table>

</div>

<div class="row text-center">
	<%= link_to 'new actor', new_actor_path, class:"btn btn-primary" %>
</div>

app/views/actors/new.html.erb
<%= render 'form' %>

app/views/actors/show.html.erb
<div class="row">
	
	<div class="col-md-10 col-md-offset-1 text-center">
		<h3><%= @actor.fullname %> (<%= @actor.gender %>)</h3>
	</div>
	
</div>

<div class="row">
	
	<div class="col-md-10 col-md-offset-1">
		<legend>movies (<%= @actor.movies.count %>)</legend>
		<% unless @actor.movies.blank? %>
		<table class="table table-striped">
			<thead>
				<th>title</th>
				<th>year</th>
				<th>rating</th>
				<th>role</th>
			</thead>
			<tbody>
				<% @actor.roles.each do |role| %>
				<tr>
					<td><%= role.movie.title %></td>
					<td><%= role.movie.year %></td>
					<td><%= show_mpaa(role.movie) %></td>
					<td><%= role.part %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<% end %>
	</div>

</div>

<div class="row col-md-12 text-center">
	
	<hr>
	
	<%= link_to 'edit', edit_actor_path(@actor), class:'btn btn-default' %>
	<%= link_to 'back', :back, class:'btn btn-default' %>

</div>