config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, :only=>[:index]
  resources :movies do
    resources :roles
  end
  resources :trailers
  resources :actors
  resources :ratings, :except=>[:show,:index]

  root 'movies#index'

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, except:[:index,:show]
  load_and_authorize_resource

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
    # the control flow jumps to index.html.erb
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)
    respond_to do |format|
      if @movie.save
        Mailrobot.notify_movie(current_user, @movie).deliver
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params[:movie].permit(:title, :year, :mpaa, :poster,
        trailers_attributes:[:id,:address,:_destroy],
        roles_attributes:[:id, :movie_id, :actor_id, :part, :_destroy])
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
  
  def show_mpaa(movie)
    content_tag(:div, movie.mpaa, class:'label label-mpaa')
  end
  
end

app/views/movies/_form.html.erb
<div class="row col-md-10 col-md-offset-1">
	
	<h1><%= controller.action_name %> movie</h1>

	<%= simple_form_for(@movie, html:{ multipart:true, class:'form-horizontal'}, wrapper: :horizontal_form) do |f| %>
	
		<%= f.error_notification %>
		<%= f.input :title, hint:'required' %>
		<%= f.input :year, hint:'required' %>
		<%= f.input :mpaa, collection:MPAA_RATINGS, label:'MPAA rating' %>
		<%= f.input :poster, as: :file, wrapper: :horizontal_file_input %>
		
		<div class="row" id="trailers">
			<%= f.simple_fields_for :trailers do |trailer| %>
				<%= render 'trailer_fields', :f=>trailer %>
			<% end %>
			<%= link_to_add_association 'add trailer', f, :trailers, class:'btn btn-sm btn-default' %>
		</div>
		
		<div class="row" id="roles">
			<%= f.simple_fields_for :roles do |role| %>
				<%= render 'role_fields', :f=>role %>
			<% end %>
			<%= link_to_add_association 'add role', f, :roles, class:'btn btn-sm btn-default' %>
		</div>
		
		<div class="row text-center">
			<%= f.submit nil, class:'btn btn-primary'%>
			<%= link_to 'cancel', :back, class:'btn btn-default' %>
		</div>

	<% end %>

</div>

app/views/movies/_movie.html.erb
<tr>
	<td><%= image_tag movie.poster.url(:thumb) %></td>
	<td><%= movie.title %></td>
	<td><%= movie.year %></td>
	<td><%= show_mpaa(movie) %></td>
  <td>
		<%= link_to fa_icon('eye'), movie %>
  	<%= link_to fa_icon('pencil'), edit_movie_path(movie) if can? :update, movie %>
  	<%= link_to fa_icon('trash-o', text:'destroy'), movie, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-xs btn-danger' if can? :destroy, movie %>
	</td>
</tr>

app/views/movies/_role_fields.html.erb
<div class="row">
	
	<div class="nested-fields">
		
		<div class="col-xs-11">
			<%= f.input :part %>
			<%= f.association :actor, collection:Actor.all, label_method: :fullname %>
		</div>
		<div class="col-xs-1">
			<%= link_to_remove_association 'remove role', f, class:'btn btn-sm btn-danger' %>
		</div>
		
	</div>
	
</div>

app/views/movies/_trailer_fields.html.erb
<div class="row">
	
	<div class="nested-fields">
		
		<div class="col-xs-11">
			<%= f.input :address %>
		</div>
		<div class="col-xs-1">
			<%= link_to_remove_association 'remove trailer', f, class:'btn btn-sm btn-danger' %>
		</div>
		
	</div>
	
</div>

app/views/movies/edit.html.erb
<%= render 'form' %>

app/views/movies/index.html.erb
<h1>Listing movies</h1>

<table class="table table-striped">
  <thead>
    <tr>
			<th>poster</th>
      <th>title</th>
			<th>year</th>
			<th>rating</th>
			<th>actions</th>
    </tr>
  </thead>

  <tbody>
		<%= render @movies %>
  </tbody>
</table>

<br>

<%= link_to 'new movie', new_movie_path, class:'btn btn-sm btn-primary' if can? :create, Movie %>
<%= link_to 'new trailer', new_trailer_path, class:'btn btn-sm btn-default' if can? :create, Trailer %>
<%= link_to 'cancel', :back, class:'btn btn-sm btn-default' %>

app/views/movies/new.html.erb
<%= render 'form' %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

	<h3 class="text-center"><%= @movie.title %></h3>
	<h5 class="text-center text-muted"><%= @movie.year %> <%= show_mpaa(@movie) %></h3>
		
	<div class="row text-center">
		<%= image_tag @movie.poster.url(:medium) %>
	</div>
	
</div>

<div class="row">
	<div class="col-md-3 col-xs-3">
		first column
	</div>
	<div class="col-md-3 col-xs-3">
		second column
	</div>
	<div class="col-md-3 col-xs-3">
		third column
	</div>
	<div class="col-md-3 col-xs-3">
		fourth column
	</div>
</div>

<div class="row">
	<div class="col-xs-5 col-xs-offset-1">	
	<h5>trailers</h5>
	<% @movie.trailers.each do |trailer| %>
		<div>
			<iframe width="210" height="162" src="http://www.youtube.com/embed/<%= trailer.address.split('=').last %>" frameborder="0" allowfullscreen></iframe>
		</div>
	<% end %>
	</div>
	<div class="col-xs-5">
	<h5>actors</h5>
	<table>
	<% @movie.roles.each do |role| %>
		<tr>
			<td><%= role.actor.first %> <%= role.actor.last %></td>
			<td><%= role.part %></td>
		</tr>
	<% end %>
	</table>
	</div>
</div>

<div class="row">
	<div>Average Rating: <%= @movie.ratings.average(:score) %></div>
	<div>My Rating: <%= show_current_user_rating(@movie) %></div>
</div>

<div class="row text-center">
	<% if can? :update, @movie %>
		<%= link_to 'edit', edit_movie_path(@movie), class:'btn btn-primary' %>
		<%= link_to 'rate', new_rating_path(movie_id:@movie.id), class:'btn btn-default' %>
	<% end %>
	<%= link_to 'back', :back, class:'btn btn-default' %>
	<% if can? :create, Role %>
		<%= link_to 'add role', new_movie_role_path(@movie), class:'btn btn-success' %>
	<% end %>
</div>